### PR TITLE
Add Ctrl-alt-t to launch terminal

### PR DESCRIPTION
**Pull request by lallenlowe**
Cheers!

### CODE REVIEW

**Comment by lallenlowe** [comment]
I had to read the gnome-control-center source code to find that dconf path, lol.

**Comment by lallenlowe** [comment]
aaaaand, I just realized I could have found it using `dconf watch` haha

**Comment by lallenlowe** [comment]
OK, tested that in Fedora Silverblue 35, working now.

**Comment by castrojo** [comment]
Ok thanks for this, I also optionally have auto-building and setting of the shortcuts via distrobox in `02-integrations.sh` but this is an excellent default!

**Pull request merged**
